[project]
name = "lsf-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annotated-types==0.7.0",
    "anyascii==0.3.3",
    "asgiref==3.12.1",
    "beautifulsoup4==4.15.0",
    "certifi==2026.6.17",
    "charset-normalizer==3.4.9",
    "croniter>=6.2.4",
    "defusedxml==0.7.1",
    "django==5.2.16",
    "django-filter==26.1",
    "django-modelcluster==6.5",
    "django-ninja==1.6.2",
    "django-permissionedforms==0.1",
    "django-q2==1.10.0",
    "django-stubs-ext==6.0.7",
    "django-taggit==6.1.0",
    "django-tasks==0.12.0",
    "django-treebeard==5.3.0",
    "djangorestframework==3.17.1",
    "draftjs-exporter==5.2.0",
    "et-xmlfile==2.0.0",
    "filetype==1.2.0",
    "gunicorn==21.2.0",
    "idna==3.18",
    "laces==0.1.2",
    "manage-py>=0.2.10",
    "modelsearch==1.3.1",
    "mysqlclient==2.2.8",
    "openpyxl==3.1.5",
    "packaging==26.2",
    "pillow==11.3.0",
    "pillow-heif==1.4.0",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "pymysql==1.2.0",
    "python-dotenv==1.2.2",
    "requests==2.34.2",
    "run>=0.3",
    "runserver>=1.0.4",
    "setuptools==83.0.0",
    "soupsieve==2.9",
    "sqlparse==0.5.5",
    "telepath==0.3.1",
    "typing-extensions==4.16.0",
    "typing-inspection==0.4.2",
    "tzdata==2026.3",
    "urllib3==2.7.0",
    "wagtail==7.4.2",
    "wheel==0.47.0",
    "whitenoise==6.12.0",
    "willow==1.12.0",
]
