# Generated by Django 5.2.16 on 2026-07-19 23:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(editable=False, max_length=16, unique=True)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuildApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=64)),
                ('class_name', models.CharField(choices=[('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('enchanter', 'Enchanter'), ('magician', 'Magician'), ('monk', 'Monk'), ('necromancer', 'Necromancer'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('shadowknight', 'Shadowknight'), ('shaman', 'Shaman'), ('warrior', 'Warrior'), ('wizard', 'Wizard')], max_length=24)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65)])),
                ('discord_name', models.CharField(max_length=80)),
                ('timezone_name', models.CharField(default='Eastern Time', max_length=80)),
                ('typical_play_times', models.CharField(max_length=200)),
                ('experience', models.TextField(blank=True)),
                ('why_join', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.CharField(max_length=280)),
                ('body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Guild news',
                'ordering': ['-pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=16)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='screenshots/%Y/%m/')),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-featured', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=64, unique=True)),
                ('character_type', models.CharField(choices=[('main', 'Main'), ('alt', 'Alt')], default='main', max_length=8)),
                ('class_name', models.CharField(choices=[('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('enchanter', 'Enchanter'), ('magician', 'Magician'), ('monk', 'Monk'), ('necromancer', 'Necromancer'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('shadowknight', 'Shadowknight'), ('shaman', 'Shaman'), ('warrior', 'Warrior'), ('wizard', 'Wizard')], max_length=24)),
                ('race', models.CharField(blank=True, max_length=40)),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65)])),
                ('rank', models.CharField(choices=[('recruit', 'Recruit'), ('member', 'Member'), ('raider', 'Raider'), ('officer', 'Officer'), ('leader', 'Guild Leader')], default='member', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('raider', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate)),
                ('bio', models.TextField(blank=True)),
                ('main_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_characters', to='guild.guildmember')),
            ],
            options={
                'ordering': ['character_name'],
            },
        ),
        migrations.CreateModel(
            name='LootRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_name', models.CharField(max_length=160)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('npc', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loot_records', to='guild.guildmember')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['-awarded_at'], name='guild_lootr_awarded_055adc_idx'), models.Index(fields=['item_name'], name='guild_lootr_item_na_fc21cf_idx')],
            },
        ),
    ]
