# Generated by Django 5.2.16 on 2026-07-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootrecord',
            name='toon_type',
            field=models.CharField(choices=[('main', 'Main'), ('alt', 'Alt')], default='main', editable=False, max_length=8),
        ),
        migrations.AddIndex(
            model_name='lootrecord',
            index=models.Index(fields=['member'], name='guild_lootr_member__1b6fde_idx'),
        ),
        migrations.AddIndex(
            model_name='lootrecord',
            index=models.Index(fields=['toon_type'], name='guild_lootr_toon_ty_3511ac_idx'),
        ),
    ]
