# Generated by Django 5.2.16 on 2026-07-20 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_lootrecord_toon_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootrecord',
            name='toon_type',
            field=models.CharField(choices=[('main', 'Main'), ('alt', 'Alt')], editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='RaidAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_attendances', to='guild.guildmember')),
                ('raid_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='guild.raidevent')),
            ],
            options={
                'ordering': ['raid_event__start_at', 'member__character_name'],
                'unique_together': {('raid_event', 'member')},
            },
        ),
    ]
