# Generated by Django 5.2.16 on 2026-07-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_alter_lootrecord_toon_type_raidattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildapplication',
            name='class_name',
            field=models.CharField(choices=[('bard', 'Bard'), ('beastlord', 'Beastlord'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('enchanter', 'Enchanter'), ('magician', 'Magician'), ('monk', 'Monk'), ('necromancer', 'Necromancer'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('shadowknight', 'Shadowknight'), ('shaman', 'Shaman'), ('warrior', 'Warrior'), ('wizard', 'Wizard')], max_length=24),
        ),
        migrations.AlterField(
            model_name='guildmember',
            name='class_name',
            field=models.CharField(choices=[('bard', 'Bard'), ('beastlord', 'Beastlord'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('enchanter', 'Enchanter'), ('magician', 'Magician'), ('monk', 'Monk'), ('necromancer', 'Necromancer'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('shadowknight', 'Shadowknight'), ('shaman', 'Shaman'), ('warrior', 'Warrior'), ('wizard', 'Wizard')], max_length=24),
        ),
    ]
