# Generated by Django 5.2.16 on 2026-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_alter_guildapplication_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidattendance',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
