# Generated by Django 5.2.16 on 2026-07-20 12:35

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0005_raidattendance_arrival_time'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guildnews',
            options={'ordering': ['-published_at'], 'verbose_name': 'Guild news story', 'verbose_name_plural': 'Guild news stories'},
        ),
        migrations.RemoveField(
            model_name='guildnews',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='guildnews',
            name='published',
        ),
        migrations.AddField(
            model_name='guildnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildnews',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show this story more prominently on the homepage.'),
        ),
        migrations.AddField(
            model_name='guildnews',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='guildnews',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guildnews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guildnews',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guildnews',
            name='slug',
            field=models.SlugField(help_text='Used in the public news story URL.', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='guildnews',
            name='summary',
            field=models.CharField(blank=True, help_text='Short description shown on the homepage and news listing.', max_length=400),
        ),
        migrations.AlterField(
            model_name='guildnews',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
