# Generated by Django 5.2.16 on 2026-07-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_alter_guildnews_options_remove_guildnews_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildmember',
            name='last_raid_attended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
