# Generated by Django 5.2.16 on 2026-07-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0007_guildmember_last_raid_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootrecord',
            name='raid_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loot_records', to='guild.raidevent'),
        ),
    ]
