# Generated by Django 5.2.16 on 2026-07-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0008_lootrecord_raid_event'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lootrecord',
            name='guild_lootr_awarded_055adc_idx',
        ),
        migrations.RemoveIndex(
            model_name='lootrecord',
            name='guild_lootr_item_na_fc21cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='lootrecord',
            name='guild_lootr_member__1b6fde_idx',
        ),
        migrations.RemoveIndex(
            model_name='lootrecord',
            name='guild_lootr_toon_ty_3511ac_idx',
        ),
    ]
