# Generated by Django 5.2.16 on 2026-07-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0009_remove_lootrecord_guild_lootr_awarded_055adc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootrecord',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
