# Generated by Django 5.2.16 on 2026-08-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0010_lootrecord_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidattendance',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
