# Generated by Django 5.2.16 on 2026-08-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0011_raidattendance_leave_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidattendance',
            name='total_raid_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
