# Generated by Django 5.2.16 on 2026-08-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0012_raidattendance_total_raid_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidattendance',
            name='attendance_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
