# Generated by Django 5.2.16 on 2026-09-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0013_raidattendance_attendance_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRaidSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, default='TBD', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('public', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recurring raid schedule',
                'verbose_name_plural': 'Recurring raid schedules',
                'ordering': ('weekday', 'start_time', 'title'),
            },
        ),
        migrations.AddField(
            model_name='raidevent',
            name='recurring_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_raids', to='guild.recurringraidschedule'),
        ),
    ]
